### ISSUE TITLE
Dev host not found in people frontend

### ISSUE THREAD

**Issue by FedeG** [lelylan/people#42]
In **app/helpers/application_helper.rb**, use **LELYLAN_DEV_URL** and **LELYLAN_DEV_PORT** but this environment variables isn't in documentation.

[Code](https://github.com/lelylan/people/blob/48bf3d347685222cf8f04eb75bc586cdb7b08d5d/app/helpers/application_helper.rb#L15)

**Comment by andreareginato** [comment]
These are the info related to the dev center.

**Comment by FedeG** [comment]
This configuration is valid?
```bash
LELYLAN_DEV_URL=https://dev.lelylan.com
LELYLAN_DEV_PORT=80
```

**Comment by andreareginato** [comment]
Yes. But would be better to have the local dev center running, although it's a bit strange to have this link to the dev center.

**Comment by FedeG** [comment]
In the [lelylan/lelylan](https://github.com/lelylan/lelylan) repository, you don't have dev center, devices dashboard or types dashboard.
You want add this services to lelylan/lelylan en development mode?

**Comment by andreareginato** [comment]
Yes @FedeG. They should get in, to make it possible to have the whole working configuration in the dev mode. Thanks.

**Comment by FedeG** [comment]
@andreareginato @lelylan/core :arrow_up:

**Comment by FedeG** [comment]
-> https://github.com/lelylan/lelylan/issues/150 -> https://github.com/Devecoop/lelylan/commit/b1ad477251888d3e65cac91233c43e27e4d76ac0
-> https://github.com/lelylan/lelylan/issues/147 -> https://github.com/Devecoop/lelylan/commit/51fff08537ec5bfa6347d6567091fd4798233a52
